compile: 
	../MP-SPDZ/compile.py prida.mpc

run:
	../MP-SPDZ/Scripts/compile-run.py -E spdz2k prida.mpc

run0:
	../MP-SPDZ/Scripts/../spdz2k-party.x 0 prida -pn 12501 -h localhost -N 2

run1:
	../MP-SPDZ/Scripts/../spdz2k-party.x 1 prida -pn 12501 -h localhost -N 2
	